"""Initial revision

Revision ID: 11144730e4d0
Revises: 23387cd22523
Create Date: 2025-01-02 12:53:02.631065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11144730e4d0'
down_revision: Union[str, None] = '23387cd22523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.drop_index('ix_groups_slug', table_name='groups')
    op.create_index(op.f('ix_groups_worker_id'), 'groups', ['worker_id'], unique=False)
    op.create_foreign_key(None, 'groups', 'workers', ['worker_id'], ['id'])
    op.drop_column('groups', 'slug')
    op.drop_index('ix_workers_slug', table_name='workers')
    op.drop_column('workers', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_index('ix_workers_slug', 'workers', ['slug'], unique=1)
    op.add_column('groups', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_worker_id'), table_name='groups')
    op.create_index('ix_groups_slug', 'groups', ['slug'], unique=1)
    op.drop_column('groups', 'worker_id')
    # ### end Alembic commands ###
